### ISSUE TITLE
It is recommended to add a custom position

### ISSUE THREAD

**Issue by BGOnline-CN** [kevlatus/ngx-drawer-layout#290]

**Comment by kevlatus** [comment]
Thanks for your feedback.
Could you please describe in more detail, what the expected behavior is?

**Comment by BGOnline-CN** [comment]
like this [antd drawer](https://ng.ant.design/components/drawer/en) 
Can control where it appears, 'top' | 'right' | 'bottom' | 'left'

**Comment by kevlatus** [comment]
"left" and "right" are already implemented.
You can open the start/left, end/right drawer or even both using the [DrawerService](https://github.com/kevlatus/ngx-drawer-layout/blob/master/projects/drawer-layout/src/lib/drawer.service.ts#L16)

According to the Material Design specification, which this library tries to implement, there is only a "bottom" drawer, but no "top" drawer.

therefore, closing this in favor of #299
